apiVersion: v1
kind: Pod
metadata:
  name: node-selector
  labels:
    purpose: node-selector-practice
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector: 
    disktype: ssd