apiVersion: v1
kind: Pod
metadata: 
  name: taints-tolerations
  labels:
    purpose: taints-tolerations-practice
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd
  tolerations:
  - key: "name"
    operator: "Equal"
    value: "praneeth"
    effect: "NoSchedule"
  - key: "age"
    operator: "Equal"
    value: "24"
    effect: "NoExecute"
