apiVersion: v1
kind: Pod
metadata: 
  name: taints-tolerations
  labels:
    purpose: taints and tolerations practice
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  
