apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-preferred
  labels:
    purpose: node-anti-affinity-preferred-practice
    project: roboshop
spec:
  affinity:
    nodeAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: hardware
            operator: NotIn
            values: 
            - gpu
  containers:
  - name: nginx
    image: nginx
